### ISSUE TITLE
Add global toggle to enable/disable cache time

### ISSUE THREAD

**Issue by capossele** [iotaledger/goshimmer#1109]
Add a global toggle to enable/disable cache time of the object storage. When `disabled` all storages that are created should be used with a cache time of 0 (cache disabled). The default should be `enabled`. 

Make use of this new functionality:
- [ ] in unit tests
- [ ] add a flag (eg `--database.disableCacheTime`) and set it by default for the integration tests
- [ ] possibly set the flag also for the Docker network?

*EDIT*:
flagi `---globalCacheTime` and any non-negative value will set all the cache to that value. A negative value will keep defaults.

**Comment by GalRogozinski** [comment]
Change in hive.go so that we can configure it for any unit test

**Comment by GalRogozinski** [comment]
#### Tasks
- [ ] add a consts file that will include all current magic numbers for cache
- [ ] Add an `-overrideCacheTime` flag for database plugin
- [ ] Add a utility function that sets the cacheTime according to hardcoded consts, and the flag.
- [ ] Add a TestMain for each package that will point to a common `setup` and `teardown` methods. Make sure `setup` will also load the `-overrideCacheTime` with a 0 default.
- [ ] Ensure integration tests will run with a 0 cache time by default
