### ISSUE TITLE
Move scheduling after booking

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/goshimmer#1481]
## Details

In order to avoid various inconsistencies, the scheduler should control what is being gossiped instead of what is being booked.

The desired data flow should look the following:
```
solidifier -> booker -> scheduler -> orderer -> gossip
                     -> consensus -> set tips
                     -> approval weight
                     -> chat
```

## Tasks

  - [x] Reattach events #1414
  - [x] Move the `orderer` between `scheduler` and `gossip`
    - [x] [low] It is then no longer needed to wait for the ordered or scheduler during shutdown
    - [x] refactor orderer, listen to gossip event (create one if it does not exist) instead of `MessageBooked` 
  - [x] Disable fifo-scheduler switcher and remove fifo scheduler
    - [ ] [low] Check behavior during heavy syncing, if this causes issues (blacklisting) consider disabling/bypassing scheduler complete during sync (test if this slow down the scheduler)
