### ISSUE TITLE
Integrate rate setter into dataflow

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/goshimmer#1482]
## Overview

Since nodes do not always have messages to issue, always scheduling at the node's max allowed share is not feasible. The rate setter allows nodes to better utilize network resources without causing excessive congestion and violating any requirement.
It uses AIMD to determine the rate at which new messages can be issued to the network. As such, the rate setter serves as some kind of queue. The data flow needs to be adapted to separate the actual message creation from the issuing intend.

## Tasks

- [ ] Rate setting needs to happen after message issuing and before message creation
  - [ ] The rate setter only takes `Payload` as input.
  - [ ] Once a payload is ready to be scheduled, it triggers the `Message` creation before passing it to the Parser
  - [ ] The spammer needs to make sure that it respects the estimate
    - [ ] Or set a timer to the current estimate for the next spam
  - [ ] Check and test the parameters

**Comment by Wollac** [comment]
Let's revisit that once the new data flow is implemented. It makes sense to also test those two together.

**Comment by piotrm50** [comment]
The task consists of the following:

[ ] Update and enable rate setter. This part will be implemented in two steps:
   [ ] Aggregate created messages in rate setter - already implemented so this will be a quick and dirty solution.
   [ ] Aggregate payloads in rate setter and create messages afterwards. This will be implemented as a second step because it requires changing other parts of code which depend on MessageID being returned immediately.
[ ] Add ratesetter estimate to web API endpoint `/ratesetter`
[ ] Update spammer to be throttled
