### ISSUE TITLE
Scheduler Buffer Management & Data Flow

### ISSUE THREAD

**Issue by Wollac** [iotaledger/goshimmer#1796]
Integrate the following data flow:
![dataflow](https://user-images.githubusercontent.com/4930426/141313814-3e05982e-5a05-4f46-aeb8-2d5eabe1995f.png)

- [ ] Remove timestamp check from parser 
- [ ] Scheduler
  - [ ] Discard buffered messages on shutdown: no persisting or waiting for them to be scheduled
  - [ ] Enqueue messages to buffer (`Scheduler.Submit(id)`) after booking.
  - [ ] Mark messages ready (`Scheduler.Ready(id)`), when their parents are scheduled or confirmed.
  - [ ] Implement drop-head buffer policy
- [ ] Remove the ordered (ordering happens using the ready-flag) #1794
- [ ] Gossip scheduled message. This should not block the scheduler. #1794
- [ ] Tip management:
  - [x] Add scheduled messages as tips and remove its parents
  - [ ] Remove parents of confirmed messages
  - [x] Periodically remove tips with old timestamp
- [ ] Implement tip fishing in URTS, i.e. TSC-criteria #1766 (postponed)

Resources:
https://iota.cafe/t/buffer-management-for-the-icca-scheduler/1226

**Comment by Wollac** [comment]
drop-head algorithm:
```
dropHead(B, msg):
  while B.size() + msg.size() > MAX_B_SIZE:
    for each node n in Buffer:
      if B[n].size() / aMana[n] > maxScale:
        maxScale ← B[n].size() / aMana[n] 
        maxNode ← n

    B[n].popOldest()
  B[msg.issuer()].insert(msg)
```

**Comment by karimodm** [comment]
Contact persons: @Wollac , @vekkiokonio , @jonastheis , @william-fabian-sanders , @piotrm50
