### ISSUE TITLE
CC Test & Stress framework

### ISSUE THREAD

**Issue by karimodm** [iotaledger/goshimmer#1861]
If we are done implementing all the needed changes we need to battle-test this big time.
These tools should contribute to our arsenal of debug tools.

Relevant metrics (maybe a bit obsolete):
https://docs.google.com/spreadsheets/d/1BBeXCU0q0hGpa5lhPOMWQkUAFjMfj4Mcks5dg22Joek/edit#gid=0

Working doc prepared by @vekkiokonio:
https://docs.google.com/document/d/1BVNgRtSGbBrKeGwFgj_lbyN1PoTr_Ddd2GZ7l6J0nO8/edit

TODO:

Metrics (high priority):
* [x] Implement metrics monitoring through Prometheus (`metrics` plugin) (as in the spreadsheet above) (Piotr) (3)
* [x] Implement metrics monitoring through ELK stack (`remotemetrics` plugin) (as in the spreadsheet above) (Gal) (5)
* [x] Visualize metrics in Grafana (Piotr) (2)
* [ ] Prepare analysis dashboards/python scripts to analyze data in Elasticsearch (Gal, Piotr) (3)

Real network tests (with high PoW, without congestion) (high priority):
* [ ] Perform fairness  and delay measurements as in the `experiment/` branch (dissemination measure) (Angelo) (7)
* [x] Test syncing with (pre)devnet, node goes offline for a while and then comes back (Angelo) (1)

Test scenarios (optional in this sprint):
* [ ] Simulate attacks (with congestion, without PoW) 
  * [x] Spam by single low mana node (Gal, Piotr) (3)
  * [x] Spam by multiple low mana nodes (Gal, Piotr) (3)
  * [ ] Spam by single high mana node (over allowed rate)
  * [ ] Spam by multiple high mana node (over allowed rate)
  * [ ] Node issues more than proportion of its mana, but there is free bandwith as other nodes are content. 

Advanced tests (different sprint): 
* [ ] dynamic active access mana (with and without changing the code)
* [ ] experiment with 1000MPS (optional)

**Comment by karimodm** [comment]
@vekkiokonio is the congestion master
