### ISSUE TITLE
Visualizer: Fix bugs found in #1835

### ISSUE THREAD

**Issue by jkrvivian** [iotaledger/goshimmer#1877]
bugs:
- [x] Can not create edge `7bdb8a8c-f82a-4d52-9a9a-7b57b3033301` with unspecified source. Goshimmer panics. (@jkrvivian) #1920
- [x] dashboard visualizer is broken (@jkrvivian) #1907
- [x] explorer link broken (@jkrvivian) #1907 
- [ ]  DAGs visualizer freeze with too many tx spammed, because graph is to long
- [x] #1918
