### ISSUE TITLE
Secret Checklist

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/goshimmer#576]
1.  [x] Generate a snapshot file with tokens on the genesis address #578  @luca-moser 
2.  [x] Incorporate the snapshot file into the docker image and #577 @Wollac
3.  [x] Bump the network and database versions @luca-moser 
4.  [x] Update all the nodes in the testnet to the latest develop @capossele 
5.  [x] Install a faucet instance and let it use the genesis wallet @capossele 
6.  [x] Reduce bootstrap MPS
7.  [x] PR for merging everything into master

Separate (no dependency):
* [x] Update the "How to setup your goshimmer node" tutorial with the URLs of the snapshot, remote log and analysis server
* [x] Add links to the analysis server dashboard in the wiki home FAQ section
* [x] Rename testnet in the wiki with <very_secret_name>
