### ISSUE TITLE
Reevaluate worker pool usages

### ISSUE THREAD

**Issue by jonastheis** [iotaledger/goshimmer#648]
@capossele and me investigated the latest occurring deadlock and went down several rabbit holes. Finally, we discovered that our frequent usage of [`async.workerpool`](https://github.com/iotaledger/hive.go/blob/master/async/workerpool.go) in its default setting with number of workers equals number of CPU cores is fundamentally flawed. 

## Deadlock
The deadlock is caused by a neighbor dropping, getting the `gossip lock` and then waiting forever on the waitgroup in `Neighbor.Close()`. This waitgroup can't finish because the `readLoop` can't terminate because it is stuck submitting something into the `gossip inboxWorkerpool`. All the workers in `inboxWorkerpool` are stuck because they are waiting to submit something into other `workerpools` and the whole thing starts piling up through several layers of worker pools. All these workers are eventually stuck at the gossip lock leading to the overall deadlock. 

The deadlock has been fixed with #650

## Usage of worker pools
We should distinguish between 2 types of worker pools:

### 1. [`async.workerpool`](https://github.com/iotaledger/hive.go/blob/master/async/workerpool.go) 
This is based on [`ants`](https://github.com/panjf2000/ants) and is more like having a bunch of recyclable goroutines but seemingly without task queue. According to the documentation it looks like this
![image](https://user-images.githubusercontent.com/4181434/87758695-38b90100-c80d-11ea-9eae-bd116d077d81.png)

We are using ants (almost everywhere) in **blocking** mode and with only **`runtime.GOMAXPROCS(0)`**. This means that every `Submit()` into a workerpool potentially blocks because there are only a handful of goroutines working in the pool. This becomes especially evident on hardware with only 2CPU cores and fast bandwidth where there's much to handle but not enough routines to do so. This explains also the problems we were seeing on slower machines.

### 2. [`workerpool.Workerpool`](https://github.com/iotaledger/hive.go/blob/master/workerpool/workerpool.go)
This looks more like a traditional [producer-consumer implementation](https://en.wikipedia.org/wiki/Producer%E2%80%93consumer_problem) with fixed number of goroutines and an additional queue for tasks. This could be better suited for some types of actions.

## Conclusion
Usage of the ants worker pools should be reevaluated because too few goroutines lead to backpressure due to other goroutines trying to submit to the pool. Additionally, usage of non-blocking pools should be considered especially in the case of the `inboxWorkerpool` so that a connection to a neighbor can **always** be closed.

## TODOs

- [ ] Create diagram (data flow) of how worker pools are chained together when receiving a message up to solidification and evaluate where bigger pools/proper queues are necessary (e.g. more I/O bound)
- [x] Create separate non-blocking worker pools for `inboxWorkerpool` in gossip depending on the type `PacketMessageRequest` or `PacketMessage` with a higher priority given to the latter. 
- [x] Make gossip `Mutex` a `RWMutex` to increase performance due to frequent read access to the neighbor's list. Done in #649

**Comment by hmoog** [comment]
The usage of "back pressure" to rate limit earlier producers in the data flow is intended as this is the only way for the node to not "leak" resources in any of its data producing modules. These modules should essentially "wait" with handing in more data (or use a non-blocking pool that drops tasks) until the remaining parts of the node are also able to process this data.

The reason for not having queues in the ants based worker pools is the fact that once the server is overloaded in any of its modules, the queues will simply "fill up" and the worker pools will behave exactly the same way as if there were no queues at all. Queues therefore do not really add any benefits in a constant throughput regime and only add additional overhead for managing these queues (making the worker pools slower). This is also the reason why ants doesn't implement queues in the first place.

Since the throughput on nodes is usually not 100% constant but sees small fluctuations it **might** be beneficial to have relatively small queues in front of **some** workers to smooth the processing and reduce waiting time. A good rule of thumb seems to be to have queue sizes of around `2 * worker_amount`, so there is always 1 slot for the next immediate task and an additional slot that can be used to schedule a waiting task.

In general, the 2nd option (`workerpool.Workerpool`) should not be used anymore. Ants is faster and better vetted and should always be the preferred option. It still exists in the code base because hornet uses it which runs single threaded where the missing queues are actually a big performance boost.

Ultimately, we should add optional queues to the ants based implementation and completely get rid of option 2 in the long run.

**Comment by jonastheis** [comment]
> In general, the 2nd option (workerpool.Workerpool) should not be used anymore. Ants is faster and better vetted and should always be the preferred option.

I'd say it depends on the use case. The 2nd option is simply a producer-consumer implementation using Go's native channel functionality as a queue and has certainly its place somewhere. 

Overall, creating back pressure from the pools is not a bad idea. But in view that we had them very small and all of them blocking prevented even dropping a neighbor as described in `Deadlock` above. In my opinion receiving a message from a neighbor should **never block**. We should handle the interrupt, read from the socket and push it into a non-blocking queue. If the queue is full, we simply drop that message. This is what @capossele and me did in #650. 

Thinking a bit further, I think it makes sense to simplify the data flow (+ code) and process a message sequentially up to a certain point. Of course, we should have multiple workers processing messages at the same time. Looking ahead to the upcoming rate control/congestion control that is something we'll have to do anyway. A scheduler will prioritize messages and these need to be fully processed before moving on to the next. Having multiple WPs makes this not really possible.

**Comment by hmoog** [comment]
> I'd say it depends on the use case. The 2nd option is simply a producer-consumer implementation using Go's native channel functionality as a queue and has certainly its place somewhere.

I am not saying that a queue is bad, I am saying the opposite - we should add a queue to option 1. Ants is faster and better vetted than my implementation of a workerpool in option 2 and since we anyway have this little wrapper around it, it makes sense to also add a queue here, so we can use one when it makes sense. It just doesn't make much sense to have two implementations of the same thing and we at some point decided to switch to ants for these things (but didn't add queues yet).

> In my opinion receiving a message from a neighbor should never block. We should handle the interrupt, read from the socket and push it into a non-blocking queue. If the queue is full, we simply drop that message. This is what @capossele and me did in #650.

I agree - that's why we should use a nonblocking worker pool that behaves the same as the old version using `TrySubmit`.

> A scheduler will prioritize messages and these need to be fully processed before moving on to the next. Having multiple WPs makes this not really possible.

That's not really 100% correct. Multiple blocking workerpools can easily be chained and then behave like a single workerpool that just processes tasks internally in a sequential order because the backpressure anyway propagates to the first scheduler. I however agree that it is most probably more efficient (less scheduling overhead) and easier to understand if there is a single scheduler that takes care of running things in parallel vs having a separate pool in each module. We however need to be aware that this approach is only efficient if we start this sequential processing at a point in the data flow where we will not "stop early" for a large amount of tasks (i.e. after the recentBytesFilter step).

I would therefore suggest to have this "fanning out into several main workers" be part of the MessageParser after we have passed the initial filter steps and then just continue sequentially from there even getting rid of the main workers in the tangle modules.

**Comment by jonastheis** [comment]
I think this should be revisited once rate control with its scheduler is implemented. @Wollac @acha-bill
