### ISSUE TITLE
Mana Merging WIP Checklist

### ISSUE THREAD

**Issue by lzpap** [iotaledger/goshimmer#989]
TODOs:
- [x] modify the base mana amount in analysis db coloring
- [x] check how the address is printed out in cli wallet
- [x] fix TransactionID string in mana event pop-up
- [x] add timestamp to mana webapi responses
- [x] remove 0 mana but online nodes from webapi and dashboard
- [x] fix string printing of outputID in mana/pending response
- [x] mana webapi print reason in error for past vector/metadata if not present

nice to haves:
- [ ] nodeID and tx ID in mana event pop-up is clickable
- [x] `mana/all` response is sorted
